sudo: required
cache: pip
language:
- python
services:
- docker
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --system
- pipenv install --dev --system
script:
- make test
- make format
before_install:
- openssl aes-256-cbc -K $encrypted_d8254237a9b1_key -iv $encrypted_d8254237a9b1_iv
  -in deploy_key.enc -out ./deploy_key -d 
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- scp deploy.sh ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
deploy:
  provider: script
  skip_cleanup: true
  script: ssh ${DEPLOY_USER}@${DEPLOY_HOST} "cd ${DEPLOY_DIRECTORY}; bash deploy.sh"
  on:
    branch: master
