sudo: required

language: python

services:
  - docker

before_install:
- docker build -t flask-app .
- docker run -d --name app flask-app
- docker ps -a

script:
- docker exec app python -m unittest discover

after_script:
- docker rm -f app