sudo: required
cache: pip
language:
- python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --system
- pipenv install --dev --system
addons:
  ssh_known_hosts: atid.imd.ufrn.br
script:
- coverage run -m pytest
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
deploy:
  provider: script
  skip_cleanup: true
  script: ssh ${DEPLOY_USER}@${DEPLOY_HOST} "cd ${DEPLOY_DIRECTORY}/ATID-API/; bash deploy.sh"
  on:
    branch: master
