version: '2'

services:

  website:
    container_name: flask_image
    build: .
    volumes:
      - '.:/app'

  nginx:
    container_name: container_nginx
    image: "nginx:1.13.5"
    ports:
      - "5000:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on: 
      - website
    

