version: '2'

services:

  website:
    build: .
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/app'
    depends_on:
      - celery

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on: 
      - website
    
  celery:
    build: .
    command: pipenv run celery worker -A app.celery --loglevel=info
    volumes:
      - '.:/app'

  neo4j:
    image: neo4j:latest # pull the latest image
    environment:
      - NEO4J_AUTH=neo4j/enigma # configure the instance with custom username/password
      - NEO4J_HEAP_MEMORY=2048 # configure the heap memory
      - NEO4J_CACHE_MEMORY=1G # configure the cache memory
    volumes:
      - ./db/dbms:/data/dbms # provision the volumes
    ports: 
      - "7474" # expose the port for the console ui

volumes:
  dbdata:
  redis:
