"""empty message

Revision ID: 260ce6cb9b40
Revises: 840aaa9291a4
Create Date: 2018-08-29 12:24:42.957702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260ce6cb9b40'
down_revision = '840aaa9291a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados_bancarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('banco', sa.String(length=500), nullable=True),
    sa.Column('agencia', sa.String(length=500), nullable=True),
    sa.Column('conta_corrente', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proprietario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(length=500), nullable=True),
    sa.Column('cnpj', sa.String(length=500), nullable=True),
    sa.Column('nome', sa.String(length=500), nullable=False),
    sa.Column('apelido', sa.String(length=500), nullable=True),
    sa.Column('genero', sa.Integer(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('profissao', sa.String(length=500), nullable=True),
    sa.Column('identidade', sa.Integer(), nullable=True),
    sa.Column('uf_emissao', sa.String(length=500), nullable=True),
    sa.Column('orgao_emissor', sa.String(length=500), nullable=True),
    sa.Column('naturalidade', sa.String(length=500), nullable=True),
    sa.Column('nacionalidade', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('estado_civil', sa.Integer(), nullable=True),
    sa.Column('passaporte', sa.String(length=500), nullable=True),
    sa.Column('contato', sa.String(length=500), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('data_expedicao', sa.Date(), nullable=True),
    sa.Column('nome_mae', sa.String(length=500), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('id_dados', sa.Integer(), nullable=True),
    sa.Column('id_anunciante', sa.Integer(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_anunciante'], ['anunciante.id'], ),
    sa.ForeignKeyConstraint(['id_dados'], ['dados_bancarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imovel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('sub_tipo', sa.Integer(), nullable=True),
    sa.Column('quartos', sa.Integer(), nullable=True),
    sa.Column('salas', sa.Integer(), nullable=True),
    sa.Column('suites', sa.Integer(), nullable=True),
    sa.Column('banheiros', sa.Integer(), nullable=True),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.Column('iptu', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('valor_condominio', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.Column('arcondicionados', sa.Integer(), nullable=True),
    sa.Column('pavimentos_predio', sa.Integer(), nullable=True),
    sa.Column('pavimentos_apto', sa.Integer(), nullable=True),
    sa.Column('distancia_mar', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('ano_construcao', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('area_util', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('area_total', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('largura', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('comprimento', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('AC', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('codigo', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_proprietario'], ['proprietario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imovel')
    op.drop_table('proprietario')
    op.drop_table('dados_bancarios')
    # ### end Alembic commands ###
