"""empty message

Revision ID: 840aaa9291a4
Revises: 
Create Date: 2018-08-29 12:10:04.168466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840aaa9291a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cep', sa.String(length=500), nullable=False),
    sa.Column('logradouro', sa.String(length=500), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('complemento', sa.String(length=500), nullable=True),
    sa.Column('bairro', sa.String(length=500), nullable=True),
    sa.Column('uf', sa.String(length=500), nullable=True),
    sa.Column('nome_condominio', sa.String(length=500), nullable=True),
    sa.Column('numero_apto', sa.Integer(), nullable=True),
    sa.Column('municipio', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('visivel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anunciante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=500), nullable=True),
    sa.Column('cpf', sa.String(length=500), nullable=True),
    sa.Column('cnpj', sa.String(length=500), nullable=True),
    sa.Column('apelido', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('cidade', sa.String(length=500), nullable=True),
    sa.Column('genero', sa.Integer(), nullable=True),
    sa.Column('identidade', sa.String(length=500), nullable=True),
    sa.Column('uf_emissao', sa.String(length=500), nullable=True),
    sa.Column('orgao_emissor', sa.String(length=500), nullable=True),
    sa.Column('data_expedicao', sa.Date(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('nome_mae', sa.String(length=500), nullable=True),
    sa.Column('naturalidade', sa.String(length=500), nullable=True),
    sa.Column('nacionalidade', sa.String(length=500), nullable=True),
    sa.Column('senha', sa.String(length=500), nullable=True),
    sa.Column('id_endereco', sa.Integer(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anunciante')
    op.drop_table('endereco')
    # ### end Alembic commands ###
